import { type Metadata } from 'next'
import {
  ClerkProvider,
} from '@clerk/nextjs'
import "@stream-io/video-react-sdk/dist/css/styles.css";
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import Navbar from '../components/Navbar'
import ClientProvider from './meets/ClientProvider'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Clerk Next.js Quickstart',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <ClerkProvider>
      <html lang="en" suppressHydrationWarning>
        <body className={`${geistSans.variable} ${geistMono.variable}`} suppressHydrationWarning>
          <ClientProvider>
              <Navbar/>
              <main>{children}</main>
          </ClientProvider>
        </body>
      </html>
    </ClerkProvider>
  )
}